server:
  port: 8091
  servlet:
    context-path: /pdf-tools
    session:
      tracking-modes: cookie
  # 压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  # Enable HTTP/2 support, if the current environment supports it
  http2:
    enabled: true

mybatis:
  type-aliases-package: com.ledi.pdftools.entities

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdf_tools?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: LediMysql2019
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  resources:
    cache:
      cachecontrol:
        # Maximum time the response should be cached (in seconds)
        max-age: 120
        # The cache must re-validate stale resources with the server. Any expired resources must not be used without re-validating.
        must-revalidate: true
        # The resources are private and intended for a single user. They must not be stored by a shared cache (e.g CDN).
        cache-private: true
        # The resources are public and any cache may store the response.
        cache-public: true
  servlet:
    multipart:
      # Multipart file uploads are enabled by default in Spring Boot with the following property
      enabled: true
      # Write files to disk if the file size is more than 2KB.
      file-size-threshold: 2KB
      # The intermediate disk location where the uploaded files are written
      location: /usr/local/pdf_tools/upload
      # Maximum file size that can be uploaded
      max-file-size: 500MB
      # Maximum allowed multipart request size
      max-request-size: 750MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

pdf:
  tools:
    file:
      basedir: /usr/local/pdf_tools/upload/
      width: 595
      height: 842
      template:
        rectangle:
          left: 28.01
          top: 27.32
          width: 53.98
          height: 13.69
    replace:
      rectangle:
        display: false

httpClient:
  maxTotal: 200
  defaultMaxPerRoute: 50
  connectTimeout: 10000
  connectionRequestTimeout: 500
  socketTimeout: 60000
  staleConnectionCheckEnabled: true