CREATE TABLE `pdf_list_detail` (
  `pdf_detail_id` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '主键ID',
  `pdf_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'PDF ID',
  `prod_no` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品名编号',
  `declare_amount_usd` decimal(12,2) DEFAULT NULL COMMENT '美金申报价值',
  `tariff_rate` decimal(12,4) DEFAULT NULL COMMENT '关税率',
  `freight_pct` decimal(12,4) DEFAULT NULL COMMENT '运费比重',
  `declare_amount_jpy` decimal(12,2) DEFAULT NULL COMMENT '日元申报价值',
  `tariff_base` decimal(12,2) DEFAULT NULL COMMENT '关税计算基数',
  `tariff` decimal(12,2) DEFAULT NULL COMMENT '关税额',
  `tariff_rounding` decimal(12,2) DEFAULT NULL COMMENT '关税取整',
  `country_excise_tax` decimal(12,2) DEFAULT NULL COMMENT '国内消费税',
  `country_excise_tax_base` decimal(12,2) DEFAULT NULL COMMENT '国内消费税额基数',
  `country_excise_tax_amount` decimal(12,2) DEFAULT NULL COMMENT '国内消费税金额',
  `local_excise_tax_base` decimal(12,2) DEFAULT NULL COMMENT '地方消费税基数',
  `local_excise_tax_amount` decimal(12,2) DEFAULT NULL COMMENT '地方消费税金额',
  PRIMARY KEY (`pdf_detail_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO pdf_list_detail(pdf_detail_id,pdf_id,prod_no,declare_amount_usd,tariff_rate,freight_pct,declare_amount_jpy,tariff_base,tariff,tariff_rounding,
 country_excise_tax,country_excise_tax_base,country_excise_tax_amount,local_excise_tax_base,local_excise_tax_amount)
 SELECT REPLACE(UUID(),"-",""), pl.pdf_id, 'prod1', pl.prod1_declare_amount_usd, pl.prod1_tariff_rate,
 pl.prod1_freight_pct, pl.prod1_declare_amount_jpy, pl.prod1_tariff_base, pl.prod1_tariff, pl.prod1_tariff_rounding,
 pl.prod1_country_excise_tax, pl.prod1_country_excise_tax_base, pl.prod1_country_excise_tax_amount, pl.prod1_local_excise_tax_base,
 pl.prod1_local_excise_tax_amount
 FROM pdf_list AS pl;

INSERT INTO pdf_list_detail(pdf_detail_id,pdf_id,prod_no,declare_amount_usd,tariff_rate,freight_pct,declare_amount_jpy,tariff_base,tariff,tariff_rounding,
 country_excise_tax,country_excise_tax_base,country_excise_tax_amount,local_excise_tax_base,local_excise_tax_amount)
 SELECT REPLACE(UUID(),"-",""), pl.pdf_id, 'prod2', pl.prod2_declare_amount_usd, pl.prod2_tariff_rate,
 pl.prod2_freight_pct, pl.prod2_declare_amount_jpy, pl.prod2_tariff_base, pl.prod2_tariff, pl.prod2_tariff_rounding,
 pl.prod2_country_excise_tax, pl.prod2_country_excise_tax_base, pl.prod2_country_excise_tax_amount, pl.prod2_local_excise_tax_base,
 pl.prod2_local_excise_tax_amount
 FROM pdf_list AS pl;

INSERT INTO pdf_list_detail(pdf_detail_id,pdf_id,prod_no,declare_amount_usd,tariff_rate,freight_pct,declare_amount_jpy,tariff_base,tariff,tariff_rounding,
 country_excise_tax,country_excise_tax_base,country_excise_tax_amount,local_excise_tax_base,local_excise_tax_amount)
 SELECT REPLACE(UUID(),"-",""), pl.pdf_id, 'prod3', pl.prod3_declare_amount_usd, pl.prod3_tariff_rate,
 pl.prod3_freight_pct, pl.prod3_declare_amount_jpy, pl.prod3_tariff_base, pl.prod3_tariff, pl.prod3_tariff_rounding,
 pl.prod3_country_excise_tax, pl.prod3_country_excise_tax_base, pl.prod3_country_excise_tax_amount, pl.prod3_local_excise_tax_base,
 pl.prod3_local_excise_tax_amount
 FROM pdf_list AS pl;

ALTER table pdf_data_coordinate add COLUMN field_type varchar(10) null comment '字段类型（list、detail）' after page_no;

update pdf_data_coordinate set field_type='list' where id in (1,2,3,4,5,6,7,8,9,10,11,12);
update pdf_data_coordinate set field_type='detail' where id in (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36);

ALTER table pdf_data_coordinate add COLUMN field_category varchar(10) null comment '字段类别（品名1、2...）' after field_type;

update pdf_data_coordinate set field_category='prod1' where action_type=2 and field_type='detail' and field_name like 'prod1%';
update pdf_data_coordinate set field_category='prod2' where action_type=2 and field_type='detail' and field_name like 'prod2%';
update pdf_data_coordinate set field_category='prod3' where action_type=2 and field_type='detail' and field_name like 'prod3%';

update pdf_data_coordinate set field_name=concat(lower(substring(field_name, 6, 1)), substring(field_name, 7)) where field_category in ('prod1', 'prod2', 'prod3');

alter table pdf_list drop column prod1_declare_amount_usd;
alter table pdf_list drop column prod2_declare_amount_usd;
alter table pdf_list drop column prod3_declare_amount_usd;
alter table pdf_list drop column prod1_tariff_rate;
alter table pdf_list drop column prod2_tariff_rate;
alter table pdf_list drop column prod3_tariff_rate;
alter table pdf_list drop column prod1_freight_pct;
alter table pdf_list drop column prod2_freight_pct;
alter table pdf_list drop column prod3_freight_pct;
alter table pdf_list drop column prod1_declare_amount_jpy;
alter table pdf_list drop column prod2_declare_amount_jpy;
alter table pdf_list drop column prod3_declare_amount_jpy;
alter table pdf_list drop column prod1_tariff_base;
alter table pdf_list drop column prod2_tariff_base;
alter table pdf_list drop column prod3_tariff_base;
alter table pdf_list drop column prod1_tariff;
alter table pdf_list drop column prod2_tariff;
alter table pdf_list drop column prod3_tariff;
alter table pdf_list drop column prod1_tariff_rounding;
alter table pdf_list drop column prod2_tariff_rounding;
alter table pdf_list drop column prod3_tariff_rounding;
alter table pdf_list drop column prod1_country_excise_tax;
alter table pdf_list drop column prod2_country_excise_tax;
alter table pdf_list drop column prod3_country_excise_tax;
alter table pdf_list drop column prod1_country_excise_tax_base;
alter table pdf_list drop column prod2_country_excise_tax_base;
alter table pdf_list drop column prod3_country_excise_tax_base;
alter table pdf_list drop column prod1_country_excise_tax_amount;
alter table pdf_list drop column prod2_country_excise_tax_amount;
alter table pdf_list drop column prod3_country_excise_tax_amount;
alter table pdf_list drop column prod1_local_excise_tax_base;
alter table pdf_list drop column prod2_local_excise_tax_base;
alter table pdf_list drop column prod3_local_excise_tax_base;
alter table pdf_list drop column prod1_local_excise_tax_amount;
alter table pdf_list drop column prod2_local_excise_tax_amount;
alter table pdf_list drop column prod3_local_excise_tax_amount;

alter table pdf_data_coordinate add column template_name varchar(30) null comment '模板名称' after id;
update pdf_data_coordinate set template_name='AIR/IMP';

INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('100', 'SEA/IMP', 3, 'detail', 'prod7', 'declareAmountUsd', 463.25, 206.02, 520.58, 213.63, 463.25, 628.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('101', 'SEA/IMP', 4, 'detail', 'prod10', 'declareAmountUsd', NULL, NULL, NULL, NULL, 463.25, 628.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('102', 'SEA/IMP', 2, 'detail', 'prod2', 'tariffRate', 109.97, 702.00, 129.86, 709.91, 109.97, 132.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('103', 'SEA/IMP', 3, 'detail', 'prod5', 'tariffRate', 109.97, 702.00, 129.86, 709.91, 109.97, 132.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('104', 'SEA/IMP', 4, 'detail', 'prod8', 'tariffRate', NULL, NULL, NULL, NULL, 109.97, 132.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('105', 'SEA/IMP', 2, 'detail', 'prod3', 'tariffRate', 109.97, 459.00, 129.86, 466.91, 109.97, 375.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('106', 'SEA/IMP', 3, 'detail', 'prod6', 'tariffRate', 109.97, 459.00, 129.86, 466.91, 109.97, 375.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('107', 'SEA/IMP', 4, 'detail', 'prod9', 'tariffRate', NULL, NULL, NULL, NULL, 109.97, 375.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('108', 'SEA/IMP', 2, 'detail', 'prod4', 'tariffRate', 109.97, 216.00, 129.86, 223.91, 109.97, 618.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('109', 'SEA/IMP', 3, 'detail', 'prod7', 'tariffRate', 109.97, 216.00, 129.86, 223.91, 109.97, 618.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('110', 'SEA/IMP', 4, 'detail', 'prod10', 'tariffRate', NULL, NULL, NULL, NULL, 109.97, 618.09, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('111', 'SEA/IMP', 2, 'detail', 'prod2', 'declareAmountJpy', 163.69, 719.77, 224.15, 727.68, 163.69, 114.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('112', 'SEA/IMP', 3, 'detail', 'prod5', 'declareAmountJpy', 163.69, 719.77, 224.15, 727.68, 163.69, 114.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('113', 'SEA/IMP', 4, 'detail', 'prod8', 'declareAmountJpy', NULL, NULL, NULL, NULL, 163.69, 114.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('114', 'SEA/IMP', 2, 'detail', 'prod3', 'declareAmountJpy', 163.69, 476.77, 224.15, 484.68, 163.69, 357.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('115', 'SEA/IMP', 3, 'detail', 'prod6', 'declareAmountJpy', 163.69, 476.77, 224.15, 484.68, 163.69, 357.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('116', 'SEA/IMP', 4, 'detail', 'prod9', 'declareAmountJpy', NULL, NULL, NULL, NULL, 163.69, 357.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('117', 'SEA/IMP', 2, 'detail', 'prod4', 'declareAmountJpy', 163.69, 233.77, 224.15, 241.68, 163.69, 600.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('118', 'SEA/IMP', 3, 'detail', 'prod7', 'declareAmountJpy', 163.69, 233.77, 224.15, 241.68, 163.69, 600.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('119', 'SEA/IMP', 4, 'detail', 'prod10', 'declareAmountJpy', NULL, NULL, NULL, NULL, 163.69, 600.32, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('120', 'SEA/IMP', 2, 'detail', 'prod2', 'tariff', 164.17, 692.63, 224.63, 700.54, 164.17, 141.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('121', 'SEA/IMP', 3, 'detail', 'prod5', 'tariff', 164.17, 692.63, 224.63, 700.54, 164.17, 141.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('122', 'SEA/IMP', 4, 'detail', 'prod8', 'tariff', NULL, NULL, NULL, NULL, 164.17, 141.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('123', 'SEA/IMP', 2, 'detail', 'prod3', 'tariff', 164.17, 449.63, 224.63, 457.54, 164.17, 384.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('124', 'SEA/IMP', 3, 'detail', 'prod6', 'tariff', 164.17, 449.63, 224.63, 457.54, 164.17, 384.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('125', 'SEA/IMP', 4, 'detail', 'prod9', 'tariff', NULL, NULL, NULL, NULL, 164.17, 384.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('126', 'SEA/IMP', 2, 'detail', 'prod4', 'tariff', 164.17, 206.63, 224.63, 214.54, 164.17, 627.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('127', 'SEA/IMP', 3, 'detail', 'prod7', 'tariff', 164.17, 206.63, 224.63, 214.54, 164.17, 627.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('128', 'SEA/IMP', 4, 'detail', 'prod10', 'tariff', NULL, NULL, NULL, NULL, 164.17, 627.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('129', 'SEA/IMP', 2, 'detail', 'prod2', 'countryExciseTax', 164.17, 626.63, 224.63, 634.54, 164.17, 207.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('130', 'SEA/IMP', 3, 'detail', 'prod5', 'countryExciseTax', 164.17, 626.63, 224.63, 634.54, 164.17, 207.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('131', 'SEA/IMP', 4, 'detail', 'prod8', 'countryExciseTax', NULL, NULL, NULL, NULL, 164.17, 207.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('132', 'SEA/IMP', 2, 'detail', 'prod3', 'countryExciseTax', 164.17, 383.63, 224.63, 391.54, 164.17, 450.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('133', 'SEA/IMP', 3, 'detail', 'prod6', 'countryExciseTax', 164.17, 383.63, 224.63, 391.54, 164.17, 450.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('134', 'SEA/IMP', 4, 'detail', 'prod9', 'countryExciseTax', NULL, NULL, NULL, NULL, 164.17, 450.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('135', 'SEA/IMP', 2, 'detail', 'prod4', 'countryExciseTax', 164.17, 140.63, 224.63, 148.54, 164.17, 693.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('136', 'SEA/IMP', 3, 'detail', 'prod7', 'countryExciseTax', 164.17, 140.63, 224.63, 148.54, 164.17, 693.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('137', 'SEA/IMP', 4, 'detail', 'prod10', 'countryExciseTax', NULL, NULL, NULL, NULL, 164.17, 693.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('138', 'SEA/IMP', 2, 'detail', 'prod2', 'countryExciseTaxAmount', 164.17, 599.63, 224.63, 607.54, 164.17, 234.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('139', 'SEA/IMP', 3, 'detail', 'prod5', 'countryExciseTaxAmount', 164.17, 599.63, 224.63, 607.54, 164.17, 234.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('140', 'SEA/IMP', 4, 'detail', 'prod8', 'countryExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 234.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('141', 'SEA/IMP', 2, 'detail', 'prod3', 'countryExciseTaxAmount', 164.17, 356.63, 224.63, 364.54, 164.17, 477.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('142', 'SEA/IMP', 3, 'detail', 'prod6', 'countryExciseTaxAmount', 164.17, 356.63, 224.63, 364.54, 164.17, 477.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('143', 'SEA/IMP', 4, 'detail', 'prod9', 'countryExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 477.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('144', 'SEA/IMP', 2, 'detail', 'prod4', 'countryExciseTaxAmount', 164.17, 113.63, 224.63, 121.54, 164.17, 720.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('145', 'SEA/IMP', 3, 'detail', 'prod7', 'countryExciseTaxAmount', 164.17, 113.63, 224.63, 121.54, 164.17, 720.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('146', 'SEA/IMP', 4, 'detail', 'prod10', 'countryExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 720.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('147', 'SEA/IMP', 2, 'detail', 'prod2', 'localExciseTaxBase', 164.17, 560.63, 224.63, 568.54, 164.17, 273.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('148', 'SEA/IMP', 3, 'detail', 'prod5', 'localExciseTaxBase', 164.17, 560.63, 224.63, 568.54, 164.17, 273.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('149', 'SEA/IMP', 4, 'detail', 'prod8', 'localExciseTaxBase', NULL, NULL, NULL, NULL, 164.17, 273.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('150', 'SEA/IMP', 2, 'detail', 'prod3', 'localExciseTaxBase', 164.17, 316.63, 224.63, 324.54, 164.17, 517.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('151', 'SEA/IMP', 3, 'detail', 'prod6', 'localExciseTaxBase', 164.17, 316.63, 224.63, 324.54, 164.17, 517.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('152', 'SEA/IMP', 4, 'detail', 'prod9', 'localExciseTaxBase', NULL, NULL, NULL, NULL, 164.17, 517.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('153', 'SEA/IMP', 2, 'detail', 'prod4', 'localExciseTaxBase', 164.17, 73.63, 224.63, 81.54, 164.17, 760.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('154', 'SEA/IMP', 3, 'detail', 'prod7', 'localExciseTaxBase', 164.17, 73.63, 224.63, 81.54, 164.17, 760.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('155', 'SEA/IMP', 4, 'detail', 'prod10', 'localExciseTaxBase', NULL, NULL, NULL, NULL, 164.17, 760.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('156', 'SEA/IMP', 2, 'detail', 'prod2', 'localExciseTaxAmount', 164.17, 533.63, 224.63, 541.54, 164.17, 300.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('157', 'SEA/IMP', 3, 'detail', 'prod5', 'localExciseTaxAmount', 164.17, 533.63, 224.63, 541.54, 164.17, 300.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('158', 'SEA/IMP', 4, 'detail', 'prod8', 'localExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 300.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('159', 'SEA/IMP', 2, 'detail', 'prod3', 'localExciseTaxAmount', 164.17, 290.63, 224.63, 298.54, 164.17, 543.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('160', 'SEA/IMP', 3, 'detail', 'prod6', 'localExciseTaxAmount', 164.17, 290.63, 224.63, 298.54, 164.17, 543.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('161', 'SEA/IMP', 4, 'detail', 'prod9', 'localExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 543.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('162', 'SEA/IMP', 2, 'detail', 'prod4', 'localExciseTaxAmount', 164.17, 47.63, 224.63, 55.54, 164.17, 786.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('163', 'SEA/IMP', 3, 'detail', 'prod7', 'localExciseTaxAmount', 164.17, 47.63, 224.63, 55.54, 164.17, 786.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('164', 'SEA/IMP', 4, 'detail', 'prod10', 'localExciseTaxAmount', NULL, NULL, NULL, NULL, 164.17, 786.46, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('165', 'SEA/IMP', 1, NULL, NULL, NULL, 362.71, 346.80, 475.63, 360.31, 362.71, 481.69, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('166', 'SEA/IMP', 2, NULL, NULL, NULL, 374.92, 731.27, 487.84, 744.78, 374.92, 97.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('167', 'SEA/IMP', 3, NULL, NULL, NULL, 374.92, 731.27, 487.84, 744.78, 374.92, 97.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('168', 'SEA/IMP', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 374.92, 97.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('169', 'SEA/IMP', 2, NULL, NULL, NULL, 374.92, 489.27, 487.84, 502.78, 374.92, 339.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('170', 'SEA/IMP', 3, NULL, NULL, NULL, 374.92, 489.27, 487.84, 502.78, 374.92, 339.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('171', 'SEA/IMP', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 374.92, 339.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('172', 'SEA/IMP', 2, NULL, NULL, NULL, 374.92, 245.27, 487.84, 258.78, 374.92, 583.22, 112.92, 13.51, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('56', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 743.77, 565.12, 754.14, 97.63, 87.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('57', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 733.77, 565.12, 744.14, 97.63, 97.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('58', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 724.77, 565.12, 735.14, 97.63, 106.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('59', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 707.77, 565.12, 718.14, 97.63, 123.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('60', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 696.77, 565.12, 707.14, 97.63, 134.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('61', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 676.77, 565.12, 687.14, 97.63, 154.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('62', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 666.77, 565.12, 677.14, 97.63, 164.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('63', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 656.77, 565.12, 667.14, 97.63, 174.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('64', 'SEA/IMP', 1, '', NULL, NULL, 97.63, 647.77, 565.12, 658.14, 97.63, 183.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('65', 'SEA/IMP', 1, NULL, NULL, NULL, 97.63, 627.77, 565.12, 638.14, 97.63, 203.86, 467.49, 10.37, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('66', 'SEA/IMP', 1, NULL, NULL, NULL, 314.54, 604.43, 426.96, 622.47, 314.54, 219.53, 112.42, 18.04, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('67', 'SEA/IMP', 1, NULL, NULL, NULL, 319.16, 572.17, 408.15, 580.08, 319.16, 261.92, 88.99, 7.91, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('68', 'SEA/IMP', 1, NULL, NULL, NULL, 436.16, 606.91, 564.53, 613.08, 436.16, 228.92, 128.37, 6.17, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('69', 'SEA/IMP', 1, NULL, NULL, NULL, 77.16, 548.91, 205.53, 555.08, 77.16, 286.92, 128.37, 6.17, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('70', 'SEA/IMP', 1, NULL, NULL, NULL, 120.16, 109.17, 201.43, 117.08, 120.16, 724.92, 81.27, 7.91, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('71', 'SEA/IMP', 1, NULL, NULL, NULL, 298.16, 109.17, 379.43, 117.08, 298.16, 724.92, 81.27, 7.91, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('72', 'SEA/IMP', 1, NULL, NULL, NULL, 460.16, 119.17, 541.43, 127.08, 460.16, 714.92, 81.27, 7.91, NULL, NULL, NULL, NULL, NULL, 1, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('73', 'SEA/IMP', 1, 'list', NULL, 'awb', 86.12, 613.69, 153.25, 622.15, 86.12, 219.85, 67.13, 8.46, 'left', 'String', NULL, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('74', 'SEA/IMP', 1, 'list', NULL, 'num', 506.51, 614.73, 548.61, 622.34, 506.51, 219.66, 42.10, 7.61, 'right', 'Integer', NULL, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('75', 'SEA/IMP', 1, 'list', NULL, 'weight', 502.51, 604.73, 548.61, 612.34, 502.51, 229.66, 46.10, 7.61, 'right', 'Decimal', 1, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('76', 'SEA/IMP', 1, 'list', NULL, 'declareTotalAmountUsd', 451.85, 509.13, 507.00, 516.74, 451.85, 325.26, 55.15, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('77', 'SEA/IMP', 1, 'list', NULL, 'declareFreightAmountUsd', 451.85, 500.13, 507.00, 507.74, 451.85, 334.26, 55.15, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('78', 'SEA/IMP', 1, 'list', NULL, 'clearanceAmount', 463.85, 484.13, 519.00, 491.74, 463.85, 350.26, 55.15, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('79', 'SEA/IMP', 1, 'list', NULL, 'bprAmount', 451.28, 426.66, 506.66, 432.83, 451.28, 409.17, 55.38, 6.17, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('80', 'SEA/IMP', 1, 'list', NULL, 'tariff', 163.77, 394.27, 225.41, 400.44, 163.77, 441.56, 61.64, 6.17, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('81', 'SEA/IMP', 1, 'list', NULL, 'exciseTax', 163.77, 385.27, 225.41, 391.44, 163.77, 450.56, 61.64, 6.17, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('82', 'SEA/IMP', 1, 'list', NULL, 'localExciseTax', 163.77, 377.27, 225.41, 383.44, 163.77, 458.56, 61.64, 6.17, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('83', 'SEA/IMP', 1, 'list', NULL, 'taxTotalAmount', 339.77, 401.31, 401.41, 408.92, 339.77, 433.08, 61.64, 7.61, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('84', 'SEA/IMP', 1, 'list', NULL, 'usdJpyExchangeRate', 512.88, 401.41, 551.41, 409.02, 512.88, 432.98, 38.53, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('85', 'SEA/IMP', 1, 'detail', 'prod1', 'declareAmountUsd', 450.08, 312.41, 507.41, 320.02, 450.08, 521.98, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('86', 'SEA/IMP', 1, 'detail', 'prod1', 'tariffRate', 105.12, 319.92, 125.01, 327.83, 105.12, 514.17, 19.89, 7.91, 'left', 'Decimal', 0, NULL, '%', 2, 'itext');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('87', 'SEA/IMP', 1, 'detail', 'prod1', 'declareAmountJpy', 153.82, 336.92, 214.28, 344.83, 153.82, 497.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('88', 'SEA/IMP', 1, 'detail', 'prod1', 'tariff', 153.82, 311.92, 214.28, 319.83, 153.82, 522.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('89', 'SEA/IMP', 1, 'detail', 'prod1', 'countryExciseTax', 153.82, 258.92, 214.28, 266.83, 153.82, 575.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('90', 'SEA/IMP', 1, 'detail', 'prod1', 'countryExciseTaxAmount', 153.82, 234.92, 214.28, 242.83, 153.82, 599.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('91', 'SEA/IMP', 1, 'detail', 'prod1', 'localExciseTaxBase', 153.82, 197.92, 214.28, 205.83, 153.82, 636.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('92', 'SEA/IMP', 1, 'detail', 'prod1', 'localExciseTaxAmount', 153.82, 173.92, 214.28, 181.83, 153.82, 660.17, 60.46, 7.91, 'right', 'Decimal', 0, '\\', NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('93', 'SEA/IMP', 2, 'detail', 'prod2', 'declareAmountUsd', 463.25, 692.02, 520.58, 699.63, 463.25, 142.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('94', 'SEA/IMP', 2, 'detail', 'prod3', 'declareAmountUsd', 463.25, 449.02, 520.58, 456.63, 463.25, 385.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('95', 'SEA/IMP', 2, 'detail', 'prod4', 'declareAmountUsd', 463.25, 206.02, 520.58, 213.63, 463.25, 628.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('96', 'SEA/IMP', 3, 'detail', 'prod5', 'declareAmountUsd', 463.25, 692.02, 520.58, 699.63, 463.25, 142.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('97', 'SEA/IMP', 4, 'detail', 'prod8', 'declareAmountUsd', NULL, NULL, NULL, NULL, 463.25, 142.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('98', 'SEA/IMP', 3, 'detail', 'prod6', 'declareAmountUsd', 463.25, 449.02, 520.58, 456.63, 463.25, 385.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');
INSERT INTO `pdf_data_coordinate` (`id`, `template_name`, `page_no`, `field_type`, `field_category`, `field_name`, `llx`, `lly`, `urx`, `ury`, `margin_left`, `margin_top`, `width`, `height`, `align`, `data_type`, `decimal_digits`, `prefix`, `suffix`, `action_type`, `read_type`) VALUES ('99', 'SEA/IMP', 4, 'detail', 'prod9', 'declareAmountUsd', NULL, NULL, NULL, NULL, 463.25, 385.37, 57.33, 7.61, 'right', 'Decimal', 2, NULL, NULL, 2, 'aspose');




